//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ServiceDesk
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Counterparty.
    /// </summary>
    // *** Start programmer edit section *** (Counterparty CustomAttributes)

    // *** End programmer edit section *** (Counterparty CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CounterpartyE", new string[] {
            "Name as \'Name\'",
            "Surname as \'Surname\'",
            "Postion as \'Postion\'",
            "Postion.Name as \'Name\'"}, Hidden=new string[] {
            "Postion.Name"})]
    [MasterViewDefineAttribute("CounterpartyE", "Postion", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("CounterpartyL", new string[] {
            "Name as \'Name\'",
            "Surname as \'Surname\'",
            "Postion.Name as \'Name\'"})]
    public class Counterparty : ICSSoft.STORMNET.DataObject
    {

        private string fName;

        private string fSurname;

        private IIS.ServiceDesk.Postion fPostion;

        // *** Start programmer edit section *** (Counterparty CustomMembers)

        // *** End programmer edit section *** (Counterparty CustomMembers)


        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Counterparty.Name CustomAttributes)

        // *** End programmer edit section *** (Counterparty.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Counterparty.Name Get start)

                // *** End programmer edit section *** (Counterparty.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Counterparty.Name Get end)

                // *** End programmer edit section *** (Counterparty.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Counterparty.Name Set start)

                // *** End programmer edit section *** (Counterparty.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Counterparty.Name Set end)

                // *** End programmer edit section *** (Counterparty.Name Set end)
            }
        }

        /// <summary>
        /// Surname.
        /// </summary>
        // *** Start programmer edit section *** (Counterparty.Surname CustomAttributes)

        // *** End programmer edit section *** (Counterparty.Surname CustomAttributes)
        [StrLen(255)]
        public virtual string Surname
        {
            get
            {
                // *** Start programmer edit section *** (Counterparty.Surname Get start)

                // *** End programmer edit section *** (Counterparty.Surname Get start)
                string result = this.fSurname;
                // *** Start programmer edit section *** (Counterparty.Surname Get end)

                // *** End programmer edit section *** (Counterparty.Surname Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Counterparty.Surname Set start)

                // *** End programmer edit section *** (Counterparty.Surname Set start)
                this.fSurname = value;
                // *** Start programmer edit section *** (Counterparty.Surname Set end)

                // *** End programmer edit section *** (Counterparty.Surname Set end)
            }
        }

        /// <summary>
        /// Counterparty.
        /// </summary>
        // *** Start programmer edit section *** (Counterparty.Postion CustomAttributes)

        // *** End programmer edit section *** (Counterparty.Postion CustomAttributes)
        [PropertyStorage(new string[] {
                "Postion"})]
        [NotNull()]
        public virtual IIS.ServiceDesk.Postion Postion
        {
            get
            {
                // *** Start programmer edit section *** (Counterparty.Postion Get start)

                // *** End programmer edit section *** (Counterparty.Postion Get start)
                IIS.ServiceDesk.Postion result = this.fPostion;
                // *** Start programmer edit section *** (Counterparty.Postion Get end)

                // *** End programmer edit section *** (Counterparty.Postion Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Counterparty.Postion Set start)

                // *** End programmer edit section *** (Counterparty.Postion Set start)
                this.fPostion = value;
                // *** Start programmer edit section *** (Counterparty.Postion Set end)

                // *** End programmer edit section *** (Counterparty.Postion Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "CounterpartyE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CounterpartyE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CounterpartyE", typeof(IIS.ServiceDesk.Counterparty));
                }
            }

            /// <summary>
            /// "CounterpartyL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CounterpartyL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CounterpartyL", typeof(IIS.ServiceDesk.Counterparty));
                }
            }
        }
    }
}

