//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ServiceDesk
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Incident.
    /// </summary>
    // *** Start programmer edit section *** (Incident CustomAttributes)

    // *** End programmer edit section *** (Incident CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("IncidentE", new string[] {
            "ID as \'ID\'",
            "Topic as \'Topic\'",
            "Description as \'Description\'",
            "Status as \'Status\'",
            "SoveBefore as \'Sove before\'",
            "Responsible as \'Responsible\'",
            "Responsible.Name as \'Name\'",
            "Counterparty as \'Counterparty\'",
            "Counterparty.Name as \'Name\'"}, Hidden=new string[] {
            "Responsible.Name",
            "Counterparty.Name"})]
    [AssociatedDetailViewAttribute("IncidentE", "Comment", "CommentE", true, "", "Comment", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("IncidentE", "Responsible", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("IncidentE", "Counterparty", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("IncidentL", new string[] {
            "ID as \'ID\'",
            "Topic as \'Topic\'",
            "Description as \'Description\'",
            "Status as \'Status\'",
            "SoveBefore as \'Sove before\'",
            "Responsible.Name as \'Name\'",
            "Counterparty.Name as \'Name\'"})]
    public class Incident : ICSSoft.STORMNET.DataObject
    {

        private string fDescription;

        private int fID;

        private System.DateTime? fSoveBefore;

        private IIS.ServiceDesk.TStatus fStatus;

        private string fTopic;

        private IIS.ServiceDesk.Counterparty fCounterparty;

        private IIS.ServiceDesk.Responsible fResponsible;

        private IIS.ServiceDesk.DetailArrayOfComment fComment;

        // *** Start programmer edit section *** (Incident CustomMembers)

        // *** End programmer edit section *** (Incident CustomMembers)


        /// <summary>
        /// Description.
        /// </summary>
        // *** Start programmer edit section *** (Incident.Description CustomAttributes)

        // *** End programmer edit section *** (Incident.Description CustomAttributes)
        [StrLen(255)]
        public virtual string Description
        {
            get
            {
                // *** Start programmer edit section *** (Incident.Description Get start)

                // *** End programmer edit section *** (Incident.Description Get start)
                string result = this.fDescription;
                // *** Start programmer edit section *** (Incident.Description Get end)

                // *** End programmer edit section *** (Incident.Description Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Incident.Description Set start)

                // *** End programmer edit section *** (Incident.Description Set start)
                this.fDescription = value;
                // *** Start programmer edit section *** (Incident.Description Set end)

                // *** End programmer edit section *** (Incident.Description Set end)
            }
        }

        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Incident.ID CustomAttributes)

        // *** End programmer edit section *** (Incident.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Incident.ID Get start)

                // *** End programmer edit section *** (Incident.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Incident.ID Get end)

                // *** End programmer edit section *** (Incident.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Incident.ID Set start)

                // *** End programmer edit section *** (Incident.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Incident.ID Set end)

                // *** End programmer edit section *** (Incident.ID Set end)
            }
        }

        /// <summary>
        /// SoveBefore.
        /// </summary>
        // *** Start programmer edit section *** (Incident.SoveBefore CustomAttributes)

        // *** End programmer edit section *** (Incident.SoveBefore CustomAttributes)
        public virtual System.DateTime? SoveBefore
        {
            get
            {
                // *** Start programmer edit section *** (Incident.SoveBefore Get start)

                // *** End programmer edit section *** (Incident.SoveBefore Get start)
                System.DateTime? result = this.fSoveBefore;
                // *** Start programmer edit section *** (Incident.SoveBefore Get end)

                // *** End programmer edit section *** (Incident.SoveBefore Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Incident.SoveBefore Set start)

                // *** End programmer edit section *** (Incident.SoveBefore Set start)
                this.fSoveBefore = value;
                // *** Start programmer edit section *** (Incident.SoveBefore Set end)

                // *** End programmer edit section *** (Incident.SoveBefore Set end)
            }
        }

        /// <summary>
        /// Status.
        /// </summary>
        // *** Start programmer edit section *** (Incident.Status CustomAttributes)

        // *** End programmer edit section *** (Incident.Status CustomAttributes)
        public virtual IIS.ServiceDesk.TStatus Status
        {
            get
            {
                // *** Start programmer edit section *** (Incident.Status Get start)

                // *** End programmer edit section *** (Incident.Status Get start)
                IIS.ServiceDesk.TStatus result = this.fStatus;
                // *** Start programmer edit section *** (Incident.Status Get end)

                // *** End programmer edit section *** (Incident.Status Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Incident.Status Set start)

                // *** End programmer edit section *** (Incident.Status Set start)
                this.fStatus = value;
                // *** Start programmer edit section *** (Incident.Status Set end)

                // *** End programmer edit section *** (Incident.Status Set end)
            }
        }

        /// <summary>
        /// Topic.
        /// </summary>
        // *** Start programmer edit section *** (Incident.Topic CustomAttributes)

        // *** End programmer edit section *** (Incident.Topic CustomAttributes)
        [StrLen(255)]
        public virtual string Topic
        {
            get
            {
                // *** Start programmer edit section *** (Incident.Topic Get start)

                // *** End programmer edit section *** (Incident.Topic Get start)
                string result = this.fTopic;
                // *** Start programmer edit section *** (Incident.Topic Get end)

                // *** End programmer edit section *** (Incident.Topic Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Incident.Topic Set start)

                // *** End programmer edit section *** (Incident.Topic Set start)
                this.fTopic = value;
                // *** Start programmer edit section *** (Incident.Topic Set end)

                // *** End programmer edit section *** (Incident.Topic Set end)
            }
        }

        /// <summary>
        /// Incident.
        /// </summary>
        // *** Start programmer edit section *** (Incident.Counterparty CustomAttributes)

        // *** End programmer edit section *** (Incident.Counterparty CustomAttributes)
        [PropertyStorage(new string[] {
                "Counterparty"})]
        [NotNull()]
        public virtual IIS.ServiceDesk.Counterparty Counterparty
        {
            get
            {
                // *** Start programmer edit section *** (Incident.Counterparty Get start)

                // *** End programmer edit section *** (Incident.Counterparty Get start)
                IIS.ServiceDesk.Counterparty result = this.fCounterparty;
                // *** Start programmer edit section *** (Incident.Counterparty Get end)

                // *** End programmer edit section *** (Incident.Counterparty Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Incident.Counterparty Set start)

                // *** End programmer edit section *** (Incident.Counterparty Set start)
                this.fCounterparty = value;
                // *** Start programmer edit section *** (Incident.Counterparty Set end)

                // *** End programmer edit section *** (Incident.Counterparty Set end)
            }
        }

        /// <summary>
        /// Incident.
        /// </summary>
        // *** Start programmer edit section *** (Incident.Responsible CustomAttributes)

        // *** End programmer edit section *** (Incident.Responsible CustomAttributes)
        [PropertyStorage(new string[] {
                "Responsible"})]
        [NotNull()]
        public virtual IIS.ServiceDesk.Responsible Responsible
        {
            get
            {
                // *** Start programmer edit section *** (Incident.Responsible Get start)

                // *** End programmer edit section *** (Incident.Responsible Get start)
                IIS.ServiceDesk.Responsible result = this.fResponsible;
                // *** Start programmer edit section *** (Incident.Responsible Get end)

                // *** End programmer edit section *** (Incident.Responsible Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Incident.Responsible Set start)

                // *** End programmer edit section *** (Incident.Responsible Set start)
                this.fResponsible = value;
                // *** Start programmer edit section *** (Incident.Responsible Set end)

                // *** End programmer edit section *** (Incident.Responsible Set end)
            }
        }

        /// <summary>
        /// Incident.
        /// </summary>
        // *** Start programmer edit section *** (Incident.Comment CustomAttributes)

        // *** End programmer edit section *** (Incident.Comment CustomAttributes)
        public virtual IIS.ServiceDesk.DetailArrayOfComment Comment
        {
            get
            {
                // *** Start programmer edit section *** (Incident.Comment Get start)

                // *** End programmer edit section *** (Incident.Comment Get start)
                if ((this.fComment == null))
                {
                    this.fComment = new IIS.ServiceDesk.DetailArrayOfComment(this);
                }
                IIS.ServiceDesk.DetailArrayOfComment result = this.fComment;
                // *** Start programmer edit section *** (Incident.Comment Get end)

                // *** End programmer edit section *** (Incident.Comment Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Incident.Comment Set start)

                // *** End programmer edit section *** (Incident.Comment Set start)
                this.fComment = value;
                // *** Start programmer edit section *** (Incident.Comment Set end)

                // *** End programmer edit section *** (Incident.Comment Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "IncidentE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View IncidentE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("IncidentE", typeof(IIS.ServiceDesk.Incident));
                }
            }

            /// <summary>
            /// "IncidentL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View IncidentL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("IncidentL", typeof(IIS.ServiceDesk.Incident));
                }
            }
        }
    }
}

