//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ServiceDesk
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Postion.
    /// </summary>
    // *** Start programmer edit section *** (Postion CustomAttributes)

    // *** End programmer edit section *** (Postion CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("PostionE", new string[] {
            "Name as \'Name\'"})]
    [View("PostionL", new string[] {
            "Name as \'Name\'"})]
    public class Postion : ICSSoft.STORMNET.DataObject
    {

        private string fName;

        // *** Start programmer edit section *** (Postion CustomMembers)

        // *** End programmer edit section *** (Postion CustomMembers)


        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Postion.Name CustomAttributes)

        // *** End programmer edit section *** (Postion.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Postion.Name Get start)

                // *** End programmer edit section *** (Postion.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Postion.Name Get end)

                // *** End programmer edit section *** (Postion.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Postion.Name Set start)

                // *** End programmer edit section *** (Postion.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Postion.Name Set end)

                // *** End programmer edit section *** (Postion.Name Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "PostionE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PostionE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PostionE", typeof(IIS.ServiceDesk.Postion));
                }
            }

            /// <summary>
            /// "PostionL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PostionL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PostionL", typeof(IIS.ServiceDesk.Postion));
                }
            }
        }
    }
}

