//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ServiceDesk
{


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T status.
    /// </summary>
    // *** Start programmer edit section *** (TStatus CustomAttributes)

    // *** End programmer edit section *** (TStatus CustomAttributes)
    public enum TStatus
    {

        // *** Start programmer edit section *** (TStatus.Active CustomAttributes)

        // *** End programmer edit section *** (TStatus.Active CustomAttributes)
        Active,

        // *** Start programmer edit section *** (TStatus.InProgress CustomAttributes)

        // *** End programmer edit section *** (TStatus.InProgress CustomAttributes)
        InProgress,

        // *** Start programmer edit section *** (TStatus.Closed CustomAttributes)

        // *** End programmer edit section *** (TStatus.Closed CustomAttributes)
        Closed,
    }
}

