




CREATE TABLE Counterparty (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NULL,
 Surname VARCHAR(255) NULL,
 Postion UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Comment (
 primaryKey UUID NOT NULL,
 CommentText VARCHAR(255) NULL,
 Incident UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Postion (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Incident (
 primaryKey UUID NOT NULL,
 Description VARCHAR(255) NULL,
 ID INT NULL,
 SoveBefore TIMESTAMP(3) NULL,
 Status VARCHAR(10) NULL,
 Topic VARCHAR(255) NULL,
 Counterparty UUID NOT NULL,
 Responsible UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Responsible (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NULL,
 Surname VARCHAR(255) NULL,
 Postion UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMNETLOCKDATA (
 LockKey VARCHAR(300) NOT NULL,
 UserName VARCHAR(300) NOT NULL,
 LockDate TIMESTAMP(3) NULL,
 PRIMARY KEY (LockKey));


CREATE TABLE STORMSETTINGS (
 primaryKey UUID NOT NULL,
 Module VARCHAR(1000) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 "User" VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAdvLimit (
 primaryKey UUID NOT NULL,
 "User" VARCHAR(255) NULL,
 Published BOOLEAN NULL,
 Module VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 HotKeyData INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERSETTING (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMWEBSEARCH (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 "Order" INT NOT NULL,
 PresentView VARCHAR(255) NOT NULL,
 DetailedView VARCHAR(255) NOT NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERDETAIL (
 primaryKey UUID NOT NULL,
 Caption VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 ConnectMasterProp VARCHAR(255) NOT NULL,
 OwnerConnectProp VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERLOOKUP (
 primaryKey UUID NOT NULL,
 DataObjectType VARCHAR(255) NOT NULL,
 Container VARCHAR(255) NULL,
 ContainerTag VARCHAR(255) NULL,
 FieldsToView VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE UserSetting (
 primaryKey UUID NOT NULL,
 AppName VARCHAR(256) NULL,
 UserName VARCHAR(512) NULL,
 UserGuid UUID NULL,
 ModuleName VARCHAR(1024) NULL,
 ModuleGuid UUID NULL,
 SettName VARCHAR(256) NULL,
 SettGuid UUID NULL,
 SettLastAccessTime TIMESTAMP(3) NULL,
 StrVal VARCHAR(256) NULL,
 TxtVal TEXT NULL,
 IntVal INT NULL,
 BoolVal BOOLEAN NULL,
 GuidVal UUID NULL,
 DecimalVal DECIMAL(20,10) NULL,
 DateTimeVal TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ApplicationLog (
 primaryKey UUID NOT NULL,
 Category VARCHAR(64) NULL,
 EventId INT NULL,
 Priority INT NULL,
 Severity VARCHAR(32) NULL,
 Title VARCHAR(256) NULL,
 Timestamp TIMESTAMP(3) NULL,
 MachineName VARCHAR(32) NULL,
 AppDomainName VARCHAR(512) NULL,
 ProcessId VARCHAR(256) NULL,
 ProcessName VARCHAR(512) NULL,
 ThreadName VARCHAR(512) NULL,
 Win32ThreadId VARCHAR(128) NULL,
 Message VARCHAR(2500) NULL,
 FormattedMessage TEXT NULL,
 PRIMARY KEY (primaryKey));



 ALTER TABLE Counterparty ADD CONSTRAINT FK189762f3a75060508f73b7d59c05d4741ab28c8e FOREIGN KEY (Postion) REFERENCES Postion; 
CREATE INDEX Index189762f3a75060508f73b7d59c05d4741ab28c8e on Counterparty (Postion); 

 ALTER TABLE Comment ADD CONSTRAINT FK764cc66816dcea1a278d407041ce516391313786 FOREIGN KEY (Incident) REFERENCES Incident; 
CREATE INDEX Index764cc66816dcea1a278d407041ce516391313786 on Comment (Incident); 

 ALTER TABLE Incident ADD CONSTRAINT FK6a7b0bec4c6a5e7c9e615001fe823b7b41eeaf32 FOREIGN KEY (Counterparty) REFERENCES Counterparty; 
CREATE INDEX Index6a7b0bec4c6a5e7c9e615001fe823b7b41eeaf32 on Incident (Counterparty); 

 ALTER TABLE Incident ADD CONSTRAINT FK7d1bd05cc796be19c02518ba6cffd1f67edba27e FOREIGN KEY (Responsible) REFERENCES Responsible; 
CREATE INDEX Index7d1bd05cc796be19c02518ba6cffd1f67edba27e on Incident (Responsible); 

 ALTER TABLE Responsible ADD CONSTRAINT FKd8f695abec4d5688219eaabddae9e2e14b59f97d FOREIGN KEY (Postion) REFERENCES Postion; 
CREATE INDEX Indexd8f695abec4d5688219eaabddae9e2e14b59f97d on Responsible (Postion); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FKc4378e39870eb056aec84088683297a01d2a6200 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FK921d16269835017e2a0d0e29ad6fb175454a70d0 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FKce38ef0db3f01a53acaa49fed8853fb941ad47ba FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

